"""Add safety_level and purposes

Revision ID: e947615dbf1b
Revises: 20260712_0007
Create Date: 2026-07-13 11:22:51.231294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e947615dbf1b'
down_revision: Union[str, None] = '20260712_0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_ingredients_inci_name'), 'ingredients', ['inci_name'])
    op.drop_column('ingredients', 'purposes')
    op.drop_column('ingredients', 'safety_level')
    # ### end Alembic commands ###
